//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_parameter
    {
        public string transaction_id { get; set; }
        public string transaction_description { get; set; }
        public Nullable<decimal> min_value { get; set; }
        public Nullable<decimal> max_value { get; set; }
        public string unit { get; set; }
        public string default_password { get; set; }
    }
}
