//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_login
    {
        public long ID { get; set; }
        public string rep_id { get; set; }
        public string hostname { get; set; }
        public string ip_addressv4 { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string created_by { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public string source { get; set; }
    }
}
