//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_bo
    {
        public m_bo()
        {
            this.m_sbo = new HashSet<m_sbo>();
        }
    
        public int bo_id { get; set; }
        public string bo_code { get; set; }
        public Nullable<int> reg_id { get; set; }
        public string bo_description { get; set; }
        public string bo_address { get; set; }
        public Nullable<int> bo_sequence_code { get; set; }
        public string bo_am { get; set; }
        public Nullable<int> bo_status { get; set; }
        public string bo_area { get; set; }
    
        public virtual m_regional m_regional { get; set; }
        public virtual ICollection<m_sbo> m_sbo { get; set; }
    }
}
