//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_doctor
    {
        public m_doctor()
        {
            this.t_visit = new HashSet<t_visit>();
            this.t_sales = new HashSet<t_sales>();
        }
    
        public int dr_code { get; set; }
        public string dr_sbo { get; set; }
        public string dr_name { get; set; }
        public string dr_type { get; set; }
        public string dr_spec { get; set; }
        public string dr_sub_spec { get; set; }
        public string dr_quadrant { get; set; }
        public Nullable<int> cust_id { get; set; }
        public string dr_address { get; set; }
        public string dr_area_mis { get; set; }
        public Nullable<int> dr_sum { get; set; }
        public string dr_category { get; set; }
        public string dr_sub_category { get; set; }
        public string dr_chanel { get; set; }
        public string dr_day_visit { get; set; }
        public string dr_visiting_hour { get; set; }
        public Nullable<int> dr_number_patient { get; set; }
        public string dr_kol_not { get; set; }
        public string dr_gender { get; set; }
        public string dr_phone { get; set; }
        public string dr_email { get; set; }
        public Nullable<System.DateTime> dr_birthday { get; set; }
        public string dr_dk_lk { get; set; }
        public Nullable<int> dr_used_session { get; set; }
        public Nullable<int> dr_used_remaining { get; set; }
        public Nullable<int> dr_used_month_session { get; set; }
        public Nullable<int> dr_status { get; set; }
        public Nullable<int> dr_sales_session { get; set; }
        public Nullable<int> dr_sales_month_session { get; set; }
        public string dr_sign { get; set; }
        public Nullable<System.DateTime> dr_last_updated { get; set; }
    
        public virtual ICollection<t_visit> t_visit { get; set; }
        public virtual ICollection<t_sales> t_sales { get; set; }
    }
}
