//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_event
    {
        public int event_id { get; set; }
        public string event_description { get; set; }
        public string event_detail_description { get; set; }
        public string event_scale { get; set; }
        public string event_place { get; set; }
        public string event_sp { get; set; }
        public string event_budget { get; set; }
        public Nullable<System.DateTime> event_date_saved { get; set; }
        public string event_saved_by { get; set; }
        public Nullable<System.DateTime> event_last_updated { get; set; }
        public string event_last_updated_by { get; set; }
        public Nullable<int> event_status { get; set; }
    }
}
