//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_gl_cs
    {
        public string o_id { get; set; }
        public string o_description { get; set; }
        public Nullable<int> o_sbo { get; set; }
        public Nullable<int> o_status { get; set; }
        public Nullable<byte> o_budget_control { get; set; }
        public Nullable<byte> o_approval { get; set; }
        public Nullable<byte> o_budget_control_sp { get; set; }
    }
}
