//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_info_feedback_mobile
    {
        public int info_feedback_id { get; set; }
        public Nullable<int> info_feedback_type { get; set; }
        public string info_description { get; set; }
    }
}
