//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_rep
    {
        public m_rep()
        {
            this.usermobiles = new HashSet<usermobile>();
        }
    
        public string rep_id { get; set; }
        public string rep_name { get; set; }
        public string rep_fullname { get; set; }
        public string rep_position { get; set; }
        public string rep_division { get; set; }
        public string rep_email { get; set; }
        public Nullable<int> rep_minvday { get; set; }
        public Nullable<int> rep_maxvday { get; set; }
        public Nullable<int> rep_maxaddvday { get; set; }
        public string rep_bank_account { get; set; }
        public string rep_bank_code { get; set; }
        public Nullable<int> rep_status { get; set; }
        public Nullable<System.DateTime> effective_datestart { get; set; }
        public Nullable<System.DateTime> rep_inactive_date { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string updated_by { get; set; }
        public string profile_picture_path { get; set; }
    
        public virtual m_role m_role { get; set; }
        public virtual ICollection<usermobile> usermobiles { get; set; }
    }
}
