//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_regional
    {
        public m_regional()
        {
            this.m_bo = new HashSet<m_bo>();
        }
    
        public int reg_id { get; set; }
        public string reg_code { get; set; }
        public string reg_description { get; set; }
        public string reg_functionary { get; set; }
        public Nullable<int> reg_sequence_code { get; set; }
        public Nullable<int> reg_status { get; set; }
        public Nullable<int> hq_id { get; set; }
    
        public virtual ICollection<m_bo> m_bo { get; set; }
    }
}
