//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_role
    {
        public m_role()
        {
            this.m_rep = new HashSet<m_rep>();
        }
    
        public int role_id { get; set; }
        public string role_code { get; set; }
        public string role_desc { get; set; }
        public int role_status { get; set; }
    
        public virtual ICollection<m_rep> m_rep { get; set; }
    }
}
