//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_expense_attachment
    {
        public int gla_id { get; set; }
        public string hdr_id { get; set; }
        public string gla_file_name { get; set; }
        public string gla_file_path { get; set; }
        public Nullable<System.DateTime> gla_date_uploaded { get; set; }
    }
}
