//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_material_order
    {
        public string moh_id { get; set; }
        public string moh_shipping_number { get; set; }
        public string moh_receive_number { get; set; }
        public string moh_note { get; set; }
        public string moh_by { get; set; }
        public Nullable<System.DateTime> moh_date { get; set; }
        public Nullable<int> moh_status { get; set; }
        public string moh_updated_by { get; set; }
        public Nullable<System.DateTime> moh_date_updated { get; set; }
        public string moh_received_by { get; set; }
        public Nullable<System.DateTime> moh_date_received { get; set; }
        public Nullable<System.DateTime> moh_date_proceed { get; set; }
        public string moh_proceed_by { get; set; }
    }
}
