//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sales_product_actual
    {
        public long spa_id { get; set; }
        public Nullable<long> sp_id { get; set; }
        public Nullable<System.DateTime> spa_date { get; set; }
        public Nullable<long> spa_quantity { get; set; }
        public Nullable<System.DateTime> spa_date_saved { get; set; }
        public string spa_note { get; set; }
    
        public virtual t_sales_product t_sales_product { get; set; }
    }
}
