//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sales_product
    {
        public t_sales_product()
        {
            this.t_sales_product_actual = new HashSet<t_sales_product_actual>();
        }
    
        public long sp_id { get; set; }
        public string sales_id { get; set; }
        public string visit_id { get; set; }
        public string prd_code { get; set; }
        public Nullable<double> sp_prd_price { get; set; }
        public Nullable<double> sp_prd_price_bpjs { get; set; }
        public Nullable<int> sp_target_qty { get; set; }
        public Nullable<double> sp_target_value { get; set; }
        public Nullable<double> sp_sales_qty { get; set; }
        public Nullable<double> sp_sales_value { get; set; }
        public string sp_note { get; set; }
        public Nullable<int> sp_plan { get; set; }
        public Nullable<int> sp_real { get; set; }
        public Nullable<int> sp_sp { get; set; }
        public Nullable<decimal> sp_percentage { get; set; }
    
        public virtual t_sales t_sales { get; set; }
        public virtual ICollection<t_sales_product_actual> t_sales_product_actual { get; set; }
    }
}
