//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sales
    {
        public t_sales()
        {
            this.t_sales_product = new HashSet<t_sales_product>();
        }
    
        public string sales_id { get; set; }
        public string rep_id { get; set; }
        public Nullable<int> sales_date_plan { get; set; }
        public Nullable<int> sales_year_plan { get; set; }
        public Nullable<int> sales_plan { get; set; }
        public string sales_code { get; set; }
        public Nullable<int> sales_realization { get; set; }
        public string sales_info { get; set; }
        public Nullable<int> dr_code { get; set; }
        public Nullable<int> sales_plan_verification_status { get; set; }
        public string sales_plan_verification_by { get; set; }
        public Nullable<System.DateTime> sales_plan_verification_date { get; set; }
        public Nullable<int> sales_real_verification_status { get; set; }
        public string sales_real_verification_by { get; set; }
        public Nullable<System.DateTime> sales_real_verification_date { get; set; }
        public Nullable<System.DateTime> sales_date_plan_saved { get; set; }
        public Nullable<System.DateTime> sales_date_plan_updated { get; set; }
        public Nullable<System.DateTime> sales_date_realization_saved { get; set; }
        public Nullable<int> sales_product_count { get; set; }
    
        public virtual m_doctor m_doctor { get; set; }
        public virtual ICollection<t_sales_product> t_sales_product { get; set; }
    }
}
