//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shift_log
    {
        public int log_id { get; set; }
        public string visit_id { get; set; }
        public string rep_id { get; set; }
        public Nullable<System.DateTime> visit_date_plan { get; set; }
        public Nullable<System.DateTime> prev_visit_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> is_active { get; set; }
    }
}
