//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_signature_mobile
    {
        public int signature_id { get; set; }
        public string visit_id { get; set; }
        public string rep_id { get; set; }
        public Nullable<int> dr_code { get; set; }
        public Nullable<bool> sign { get; set; }
        public string file_upload { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
