//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sp_attachment
    {
        public int spf_id { get; set; }
        public string spr_id { get; set; }
        public string spf_file_name { get; set; }
        public string spf_file_path { get; set; }
        public Nullable<System.DateTime> spf_date_uploaded { get; set; }
    }
}
