//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_visit
    {
        public t_visit()
        {
            this.t_visit_product = new HashSet<t_visit_product>();
        }
    
        public string visit_id { get; set; }
        public string rep_id { get; set; }
        public Nullable<System.DateTime> visit_date_plan { get; set; }
        public Nullable<int> visit_plan { get; set; }
        public string visit_code { get; set; }
        public Nullable<int> visit_realization { get; set; }
        public string visit_info { get; set; }
        public string visit_sp { get; set; }
        public Nullable<double> visit_sp_value { get; set; }
        public Nullable<int> dr_code { get; set; }
        public Nullable<int> visit_plan_verification_status { get; set; }
        public string visit_plan_verification_by { get; set; }
        public Nullable<System.DateTime> visit_plan_verification_date { get; set; }
        public Nullable<int> visit_real_verification_status { get; set; }
        public string visit_real_verification_by { get; set; }
        public Nullable<System.DateTime> visit_real_verification_date { get; set; }
        public Nullable<System.DateTime> visit_date_plan_saved { get; set; }
        public Nullable<System.DateTime> visit_date_plan_updated { get; set; }
        public Nullable<System.DateTime> visit_date_realization_saved { get; set; }
        public Nullable<int> visit_coverage_plan { get; set; }
        public Nullable<int> visit_coverage_real { get; set; }
        public string visit_sign_id { get; set; }
        public string visit_ordinat { get; set; }
        public Nullable<int> visit_product_count { get; set; }
        public string visit_comment { get; set; }
        public Nullable<System.DateTime> visit_last_updated { get; set; }
        public Nullable<int> visit_type { get; set; }
        public Nullable<int> visit_associate_status { get; set; }
    
        public virtual ICollection<t_visit_product> t_visit_product { get; set; }
        public virtual m_doctor m_doctor { get; set; }
    }
}
