//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class usermobile
    {
        public int IdUserMobile { get; set; }
        public string rep_id { get; set; }
        public string UserToken { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual m_rep m_rep { get; set; }
    }
}
