//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_expense
    {
        public string hdr_id { get; set; }
        public string hdr_spr_no { get; set; }
        public Nullable<System.DateTime> hdr_posting_date { get; set; }
        public string hdr_daybook { get; set; }
        public string hdr_description { get; set; }
        public string hdr_acc_credit { get; set; }
        public string hdr_acc_credit_desc { get; set; }
        public string hdr_allocation_key { get; set; }
        public Nullable<byte> hdr_posting_status { get; set; }
        public string hdr_voucher_no { get; set; }
        public string hdr_payment_status { get; set; }
        public string hdr_posting_status_desc { get; set; }
        public Nullable<System.DateTime> hdr_transered_date { get; set; }
        public string hdr_posting_by { get; set; }
        public string hdr_posting_by_name { get; set; }
        public Nullable<System.DateTime> hdr_created_date { get; set; }
        public string hdr_created_by { get; set; }
        public string hdr_created_by_name { get; set; }
        public Nullable<double> total_expense { get; set; }
        public Nullable<byte> hdr_verification_status { get; set; }
        public string hdr_verified_by { get; set; }
        public Nullable<System.DateTime> hdr_date_verified { get; set; }
        public string rep_email { get; set; }
    }
}
