//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_product_price
    {
        public int price_id { get; set; }
        public string prd_aso_id { get; set; }
        public Nullable<double> hna_regular { get; set; }
        public Nullable<double> price_regular { get; set; }
        public Nullable<double> hna_bpjs { get; set; }
        public Nullable<double> price_bpjs { get; set; }
        public Nullable<System.DateTime> effective_date_start { get; set; }
        public Nullable<System.DateTime> effective_date_end { get; set; }
        public Nullable<int> price_status { get; set; }
        public string prd_code { get; set; }
        public string prd_focus { get; set; }
        public string prd_type { get; set; }
        public string visit_code { get; set; }
        public string visit_product { get; set; }
        public string visit_category { get; set; }
        public string visit_group { get; set; }
        public string visit_team { get; set; }
        public string visit_budget_ownership { get; set; }
        public string prd_aso_desc { get; set; }
        public string prd_aso_type { get; set; }
        public string prd_aso_category { get; set; }
        public Nullable<int> prd_aso_program { get; set; }
        public string prd_aso_join_desc { get; set; }
        public string prd_aso_gp { get; set; }
        public string prd_aso_ose { get; set; }
        public string prd_aso_group { get; set; }
        public string prd_aso_group_fin { get; set; }
        public Nullable<int> prd_aso_tab { get; set; }
        public Nullable<int> prd_aso_dossage { get; set; }
        public string prd_aso_dostime { get; set; }
        public string prd_aso_tc { get; set; }
        public Nullable<int> prd_status { get; set; }
    }
}
