//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rep_admin
    {
        public decimal j_id { get; set; }
        public string rep_id { get; set; }
        public string rep_name { get; set; }
        public string sbo_code { get; set; }
        public string bo_code { get; set; }
        public Nullable<int> reg_id { get; set; }
        public string rep_admin { get; set; }
        public string admin_name { get; set; }
        public string reg_code { get; set; }
        public string admin_email { get; set; }
    }
}
