//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rep_full_new
    {
        public string rep_id { get; set; }
        public string rep_full_name { get; set; }
        public string phone { get; set; }
        public string birth_place { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string address { get; set; }
        public string rep_region { get; set; }
        public string rep_sbo { get; set; }
        public string ProfilePicture { get; set; }
        public string rep_position { get; set; }
    }
}
