//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sp_product
    {
        public int spp_id { get; set; }
        public string spr_id { get; set; }
        public string sp_product { get; set; }
        public string visit_team { get; set; }
        public string visit_product { get; set; }
        public string visit_category { get; set; }
        public string visit_group { get; set; }
        public string visit_budget_ownership { get; set; }
        public string o_description { get; set; }
        public string o_department { get; set; }
        public Nullable<int> o_status { get; set; }
        public string o_functionary { get; set; }
        public Nullable<int> sp_product_ownership { get; set; }
    }
}
