//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.BAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_visit_associate
    {
        public int associate_id { get; set; }
        public string visit_id_initiator { get; set; }
        public string rep_id_initiator { get; set; }
        public Nullable<int> dr_code_initiator { get; set; }
        public string visit_id_invited { get; set; }
        public string rep_id_invited { get; set; }
        public Nullable<int> dr_code_invited { get; set; }
        public Nullable<int> associate_status { get; set; }
        public string visit_code { get; set; }
    }
}
