//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.HRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Karyawan
    {
        public string Nomor_Induk { get; set; }
        public string Nama { get; set; }
        public string Kode_Headquarter { get; set; }
        public string Kode_Departemen { get; set; }
        public string Nama_Seksi { get; set; }
        public string Kode_Bagian { get; set; }
        public string Nama_Bagian { get; set; }
        public string Singkatan_Bagian { get; set; }
        public Nullable<int> Status_Aktif { get; set; }
        public string Kode_Jabatan { get; set; }
        public string Nama_Departemen { get; set; }
        public string Email { get; set; }
        public Nullable<int> Kode_Level { get; set; }
        public string Nama_Cabang { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string id_data { get; set; }
    }
}
