//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.HRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departeman
    {
        public Departeman()
        {
            this.Karyawans = new HashSet<Karyawan>();
        }
    
        public string Kode_Departemen { get; set; }
        public string Nama_Departemen { get; set; }
        public string Kode_Headquarter { get; set; }
        public string NIK { get; set; }
        public string kd_dept_asal { get; set; }
        public string nama_dept_asal { get; set; }
        public string kd_hq_asal { get; set; }
        public string kd_hq_contrary { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string IndexID { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> Disabled { get; set; }
    
        public virtual HeadQuarter HeadQuarter { get; set; }
        public virtual ICollection<Karyawan> Karyawans { get; set; }
    }
}
