//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_DAL.HRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadQuarter
    {
        public HeadQuarter()
        {
            this.Departemen = new HashSet<Departeman>();
        }
    
        public string Kode_Headquarter { get; set; }
        public string Nama_Headquarter { get; set; }
        public string NIK { get; set; }
    
        public virtual ICollection<Departeman> Departemen { get; set; }
    }
}
